export const logos = [
  {
    key: "1",
    image: "/images/logos/benx.png",
    alt: "Benx",
    width: 144,
    height: 61,
  },
  {
    key: "2",
    image: "/images/logos/flamboyant.png",
    alt: "Flamboyant Urbanismo",
    width: 232,
    height: 64,
  },
  {
    key: "3",
    image: "/images/logos/cambur.png",
    alt: "Cambur",
    width: 206,
    height: 56,
  },
  {
    key: "4",
    image: "/images/logos/catuai.png",
    alt: "Catuai",
    width: 148,
    height: 71,
  },
  {
    key: "5",
    image: "/images/logos/cury.png",
    alt: "Cury",
    width: 169,
    height: 54,
  },
  {
    key: "6",
    image: "/images/logos/cv-haus.png",
    alt: "CV Haus",
    width: 174,
    height: 49,
  },
  {
    key: "7",
    image: "/images/logos/dialogo.png",
    alt: "Diálogo",
    width: 206,
    height: 67,
  },
  {
    key: "8",
    image: "/images/logos/ecb-group.png",
    alt: "ECB Group",
    width: 173,
    height: 67,
  },
  {
    key: "9",
    image: "/images/logos/econ.png",
    alt: "Econ",
    width: 173,
    height: 42,
  },
  {
    key: "10",
    image: "/images/logos/iguatemi.png",
    alt: "Iguatemi",
    width: 233,
    height: 57,
  },
  {
    key: "11",
    image: "/images/logos/nova-harmonia.png",
    alt: "Nova Harmonia",
    width: 139,
    height: 83,
  },
  {
    key: "12",
    image: "/images/logos/novolar.png",
    alt: "Novolar",
    width: 186,
    height: 52,
  },
  {
    key: "13",
    image: "/images/logos/p3urb.png",
    alt: "P3Urb",
    width: 79,
    height: 74,
  },
  {
    key: "14",
    image: "/images/logos/passarelli.png",
    alt: "Passareli",
    width: 249,
    height: 57,
  },
  {
    key: "15",
    image: "/images/logos/sequoia.png",
    alt: "Sequóia",
    width: 217,
    height: 35,
  },
  {
    key: "16",
    image: "/images/logos/tarraf.png",
    alt: "Tarraf",
    width: 221,
    height: 47,
  },
  {
    key: "17",
    image: "/images/logos/wanderley.png",
    alt: "Wanderley Construções",
    width: 162,
    height: 75,
  }
]